version: '3.7'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:${N8N_PORT}:5678" # <-- Reads port from .env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB} # <-- Reads from .env
      - DB_POSTGRESDB_USER=${POSTGRES_USER}     # <-- Reads from .env
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD} # <-- Reads from .env
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}             # <-- Reads from .env
      - POSTGRES_USER=${POSTGRES_USER}             # <-- Reads from .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}     # <-- Reads from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
    external: true
  postgres_data:
